### ISSUE TITLE
[feat] 알림장 CRUD 구현, 숙제 완료여부

### ISSUE THREAD

**Issue by beomzun** [Turing-mentos/Turing-BE#9]
## ✨ Description

> 알림장 CRUD

## 📌 구현 내용

- [x] 알림장 엔티티 필드 추가 - 마감일자(deadline - Timestamp)
- [x] 이번주 숙제현황 조회
- [x] 지난 알림장 전체 조회
- [x] 알림장 생성
- [x] 알림장 한 건 조회 - 간편 템플릿 / 현재 / 과거
- [x] 알림장 삭제
- [x] 알림장 수정(마감일자)
- [x] 숙제 엔티티 필드 추가 - 완료여부(isDone - Boolean)
- [x] 숙제 완료여부 수정
---
- [x] 숙제 삭제 ResponseEntity의 body type 수정
## 🌱 Etc
- 알림장 엔티티에 완료여부 필드를 추가하는게 좋을까요?
    - 추가 시 : 매 숙제 완료여부 변경시마다 해당 알림장의 모든 숙제 완료여부 확인 후 알림장 완료여부 필드 업데이트 필요
    - 현행 유지 시 : 매 숙제현황 확인시 전체 숙제의 완료여부 확인을 통해 해당 알림장 음영표시 여부 결정해야함
-

**Comment by zosungwoo** [comment]
혹시 

> 현행 유지 시 : 매 숙제현황 확인시 **전체 숙제의 완료여부 확인을 통해 해당 알림장 음영표시 여부 결정**해야함

이 부분은 앱에서 하는 걸로 생각하신 걸까요?
아니면 저희가 확인 후 따로 완료 여부를 함께 응답해주는 걸로 생각하신 걸까요?
(개인적인 생각으로는 앱에서 이걸 하게 하면 안될 것 같아요)

만약 후자라면 따로 필드 안두고 알림장 조회 시에만 확인 후 완료 여부 응답해주는 거면 뭔가 효율이(?) 가장 좋을 것 같다는 생각이 들어요! (응답 시 DTO에서만 해당 값을 다뤄도 되는 건지는 잘 모르겠지만요 ㅠㅠ)

**Comment by beomzun** [comment]
우선 양측에서 모두 가능하기에 주체를 제한하고 생각하지는 않았습니다.

자세한 이유가 궁금합니다!!
1) 앱에서 처리하는게 좋지 않을 것 같은 이유
2) 플래그 사용 시 효율이 가장 좋을 것 같다고 판단한 이유 (DTO로 여부 전달 시 플래그로 충분히 전달할 수 있다고 생각합니다!)

**Comment by zosungwoo** [comment]
1. 
<img width="200" alt="image" src="https://github.com/Turing-mentos/Turing-BE/assets/30895117/db634b66-8fbd-42e0-8c0b-e25174ca2e43">

앱 기본 진입 화면에서 모든 숙제 완료 여부에 따라 바로 1. '열고 닫음 토글'과 2. '완료' 표시를 해야해서, 프론트 입장에서는 따로 완료 여부를 받는 것이 나을 거라 생각했어요!
근데 다시 생각을 해봤는데, 어차피 앱에서 모든 체크 박스를 선택할 시 '완료' 표시가 되도록 처리를 해야하므로 굳이 필요 없을 것 같기도 합니다..!

2. 
알림장 조회 시에만 필요할 것 같은 정보인데,
이거 때문에 필드를 추가해서 숙제 완료를 체크할 때마다 모든 숙제 완료여부를 확인하고 알림장 완료여부를 업데이트하는 것보다는
알림장 조회 시에만 확인해서 전달해주는 게 더 나을 것 같다고 생각했어요
